= Predefined Values
James Elliott <james@deepsymmetry.org>
:icons: font
:toc: preamble
:experimental:

There are a number of predefined values that control the default
behavior of the functions you use to draw byte field diagrams. They
are set up as variables before your code starts running, and as
described in the <<intro#drawing-model,introduction>>, you can change
their values using https://clojuredocs.org/clojure.core/def[Clojure's
`def`] mechanism.

TIP: Unless you append a specific unit type to them,
https://oreillymedia.github.io/Using_SVG/guide/units.html[distances
and coordinates] in SVG are interpreted as "user units", which default
in these diagrams to pixels (as if you had added `px` after the
number).

[cols="1m,1m,4"]
|===
|Variable |Default Value |Purpose

|left-margin |40 | How far from the left edge of the diagram the first
 box begins. This default is large enough to accommodate the row
 address labels for all but extremely long byte fields. If you are
 drawing a single row (which won't have a row label), it's nice to set
 this to `1` so the diagram is centered.

|right-margin |1 | How far from the right edge of the diagram the last
 box ends. This default is just large enough to make sure the box
 boundary doesn't get clipped. You can make it bigger if you want to
 draw custom content there.

|bottom-margin |1 | How far from the bottom edge of the diagram the
 last row of boxes ends. This default is just large enough to make
 sure the box boundaries don't get clipped. You can make it bigger if
 you want to draw custom content there.

|box-width |1 | How much horizontal space each box takes up.

|===

include::partial$Footer.adoc[]
